### ISSUE TITLE
No Email confirmation requested when signing up

### ISSUE THREAD

**Issue by 5balls** [calthejuggler/objectepisodes.com#1]
There should definitely be a separate mail with confirmation link for people signing up to be informed about object episodes. The way it is now any Email adress can be entered and used to spam people which is not ok. I signed up and want to be informed but there should be another step in this as it is common on any other mailing list.

**Comment by calthejuggler** [comment]
Hey @5balls! I'm so sorry that I didn't see this earlier!
The way I see it, there is (and will be) an unsubscribe link on every email. Allowing anybody who has been input as spam to unsubscribe themselves. Unless you received no email at all? That would be worrying!

**Comment by calthejuggler** [comment]
I now see the naivity in my reply! I have added Google Recaptcha for extra security. Thanks for your input!

**Comment by 5balls** [comment]
Thank you very much! Sorry if the wording on my initial issue may have sounded a bit harsh - I realized later it could be read that way.
